
cards = {
            # Cards

            # Joke cards
            'pot of greed' : {  'title': 'Pot of Greed',
                                'image': 'https://i.imgur.com/fQc6cDK.png',
                                'source': 'https://www.youtube.com/watch?v=Ay_S8NjPEXk',
                                'type': 'Boost',
                                'availability': 'GameBanana',
                                'flavor': 'Let\'s be honest, Nice Present is basically Pot of Greed.'},

            'im accelerating' : {   'title': '\"I\'m accelerating.\"',
                                    'image': 'https://i.imgur.com/z893P16.png',
                                    'source': 'https://i.imgur.com/z893P16.png',
                                    'type': 'RIP',
                                    'flavor': 'But sugu can accelerate even faster, to incredible hihg speed!'},

            'very fast sugu accelerating at incredible hihg speed' : {  'title': 'VERY fast sugu accelerating at incredible hihg speed',
                                                                        'image': 'https://i.imgur.com/Aux5Xdh.png',
                                                                        'source': 'https://kakashi-nenpo.com/jp/res/16966+50.html#21686',
                                                                        'type': 'Fucking RIP',
                                                                        'flavor': 'Basically, how it feels to play Suguri half of the time.'},

            'ビット食えよおおお！！' : {  'title': 'I said eat the bits!!',
                                        'image': 'https://i.imgur.com/gIhxy8f.png',
                                        'source': 'https://i.imgur.com/gIhxy8f.png',
                                        'type': 'meme',
                                        'flavor': 'Please watch Pop Team Epic.'},

            ##################################
            # Characters
            ##################################
            'kai' : {   'title': 'Kai',
                        'image': 'https://i.imgur.com/BhoobUv.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kai',
                        'type': 'Character',
                        'hyper': 'Protagonist\'s Privilege',
                        'availability': 'Default'},

            'qp' : {    'title': 'QP',
                        'image': 'https://i.imgur.com/IJ01XOg.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/QP',
                        'type': 'Character',
                        'hyper': 'Hyper Mode',
                        'availability': 'Default',
                        'flavor': 'Also check out \"QP (Dangerous)\".'},

            'suguri' : {    'title': 'Suguri',
                            'image': 'https://i.imgur.com/zlmJhvz.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Suguri',
                            'type': 'Character',
                            'hyper': 'Accelerator',
                            'availability': 'Default',
                            'flavor': 'Also check out \"Suguri (Ver.2)\".'},

            'marc' : {      'title': 'Marc',
                            'image': 'https://i.imgur.com/uakQhfx.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marc',
                            'type': 'Character',
                            'hyper': 'x16 Big Rocket',
                            'availability': 'Default'},

            'yuki' : {      'title': 'Yuki',
                            'image': 'https://i.imgur.com/ZsYMq5D.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Yuki',
                            'type': 'Character',
                            'hyper': 'Gamble!',
                            'availability': 'Unlockable',
                            'flavor': 'Also check out \"Yuki (Dangerous)\".'},

            'aru' : {       'title': 'Aru',
                            'image': 'https://i.imgur.com/4x4rmwb.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Aru',
                            'type': 'Character',
                            'hyper': 'Present For You',
                            'availability': 'Unlockable',
                            'flavor': 'Also check out \"Aru (Scramble)\".'},

            'hime' : {      'title': 'Hime',
                            'image': 'https://i.imgur.com/SDHLGY0.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Hime',
                            'type': 'Character',
                            'hyper': 'Binding Chains',
                            'availability': 'Unlockable'},

            'sora' : {  'title': 'Sora',
                        'image': 'https://i.imgur.com/sUvoh8H.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sora',
                        'type': 'Character',
                        'hyper': 'Extraordinary Specs',
                        'availability': 'Unlockable',
                        'flavor': 'Also check out \"Sora (Military)\".'},

            'fernet' : {'title': 'Fernet',
                        'image': 'https://i.imgur.com/1qtP3sr.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Fernet',
                        'type': 'Character',
                        'hyper': 'Air Strike',
                        'availability': 'Unlockable',
                        'flavor': 'Ara ara~'},

            'peat' : {  'title': 'Peat',
                        'image': 'https://i.imgur.com/yb2Q01y.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Peat',
                        'type': 'Character',
                        'hyper': 'Blue Crow the Second',
                        'availability': 'Unlockable'},

            'marie poppo' : {   'title': 'Marie Poppo',
                                'image': 'https://i.imgur.com/FEUTA0d.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marie_Poppo',
                                'type': 'Character',
                                'hyper': 'Ubiquitous',
                                'availability': 'Unlockable',
                                'flavor': 'Also check out: \"Marie Poppo (Mixed)\", \"Marie Poppo (Boss)\".'},

            'tomomo' : {'title': 'Tomomo (Softened)',
                        'image': 'https://i.imgur.com/JKSYHJe.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo',
                        'type': 'Character',
                        'hyper': 'Magical Massacre',
                        'availability': 'Unlockable',
                        'flavor': 'This is the multiplayer version of Tomomo. For the singleplayer version, see \"Tomomo (Boss)\".'},

            'tomomo (boss)' : { 'title': 'Tomomo',
                                'image': 'https://i.imgur.com/UPx7fYA.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo',
                                'type': 'Character',
                                'hyper': 'Magical Massacre',
                                'availability': 'Unlockable',
                                'flavor': 'Also check out \"Tomomo (Casual)\".'},

            'chicken' : {   'title': 'Chicken',
                            'image': 'https://i.imgur.com/9khRFXW.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Chicken',
                            'type': 'Character',
                            'hyper': 'Golden Egg',
                            'availability': 'Unlockable',
                            'flavor': 'For the enemy, see \"Chicken (Enemy)\".'},

            'robo ball' : { 'title': 'Robo Ball',
                            'image': 'https://i.imgur.com/orn9wlz.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Robo_Ball',
                            'type': 'Character',
                            'hyper': 'Reflective Shell',
                            'availability': 'Unlockable',
                            'flavor': 'For the enemy, see \"Robo Ball (Enemy)\".'},

            'seagull' : {   'title': 'Seagull',
                            'image': 'https://i.imgur.com/IpnMufo.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Seagull',
                            'type': 'Character',
                            'hyper': 'Jonathan Rush',
                            'availability': 'Unlockable',
                            'flavor': 'For the enemy, see \"Seagull (Enemy)\".'},

            'store manager' : { 'title': 'Store Manager',
                                'image': 'https://i.imgur.com/sDT7dCK.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Store_Manager',
                                'type': 'Character',
                                'hyper': 'Banned for Life',
                                'availability': 'Unlockable',
                                'flavor': 'For the boss, see \"Store Manager (Boss)\".'},

            'shifu robot' : {   'title': 'Shifu Robot',
                                'image': 'https://i.imgur.com/QQpKI6g.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Shifu_Robot',
                                'type': 'Character',
                                'hyper': 'Turbo Charged',
                                'availability': 'Unlockable'},

            'flying castle' : { 'title': 'Flying Castle',
                                'image': 'https://i.imgur.com/VZtwURT.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Flying_Castle',
                                'type': 'Character',
                                'hyper': 'Immovable Object',
                                'availability': 'Unlockable'},

            'syura' : { 'title': 'Syura',
                        'image': 'https://i.imgur.com/Ew9dwYq.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Syura',
                        'type': 'Character',
                        'hyper': 'Beyond Hell',
                        'availability': 'DLC 1 - Syura & Nanako Character Pack'},

            'nanako' : {'title': 'Nanako',
                        'image': 'https://i.imgur.com/vsQXHi0.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Nanako',
                        'type': 'Character',
                        'hyper': 'Deploy Bits',
                        'availability': 'DLC 1 - Syura & Nanako Character Pack'},

            'saki' : {  'title': 'Saki',
                        'image': 'https://i.imgur.com/h8tKZ58.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Saki',
                        'type': 'Character',
                        'hyper': 'Big Bang Bell',
                        'availability': 'DLC 2 - Saki & Kyousuke Character Pack'},

            'kyousuke' : {  'title': 'Kyousuke',
                            'image': 'https://i.imgur.com/TJL8TRO.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kyousuke',
                            'type': 'Character',
                            'hyper': 'Cast Off',
                            'availability': 'DLC 2 - Saki & Kyousuke Character Pack'},

            'krila' : { 'title': 'Krila',
                        'image': 'https://i.imgur.com/emxzRgD.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Krila',
                        'type': 'Character',
                        'hyper': 'Plushie Master',
                        'availability': 'DLC 4 - Krila & Kae Character Pack',
                        'flavor': 'Her full name is Krilalaris.'},

            'kae' : {   'title': 'Kae',
                        'image': 'https://i.imgur.com/NIAK6uD.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kae',
                        'type': 'Character',
                        'hyper': 'Blazing!',
                        'availability': 'DLC 4 - Krila & Kae Character Pack'},

            'alte' : {  'title': 'Alte',
                        'image': 'https://i.imgur.com/iX9PTgk.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Alte',
                        'type': 'Character',
                        'hyper': 'Self-Destruct',
                        'availability': 'DLC 5 - Alte & Kyoko Character Pack'},

            'kyoko' : { 'title': 'Kyoko',
                        'image': 'https://i.imgur.com/dZ3Zjmp.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kyoko',
                        'type': 'Character',
                        'hyper': 'Crystal Barrier',
                        'availability': 'DLC 5 - Alte & Kyoko Character Pack'},

            'sham' : {  'title': 'Sham',
                        'image': 'https://i.imgur.com/GAYXQ6f.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sham',
                        'type': 'Character',
                        'hyper': 'Delta Field',
                        'availability': 'DLC 6 - Sham & Sherry Character Pack'},

            'sherry' : {'title': 'Sherry',
                        'image': 'https://i.imgur.com/7lxD1jP.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sherry',
                        'type': 'Character',
                        'hyper': 'Whimsical Windmill',
                        'availability': 'DLC 6 - Sham & Sherry Character Pack'},

            'star breaker' : {  'title': 'Star Breaker',
                                'image': 'https://i.imgur.com/4432L2z.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Star_Breaker',
                                'type': 'Character',
                                'hyper': 'Star Blasting Fuse',
                                'availability': 'DLC 7 - Breaker Pack'},

            'sweet breaker' : { 'title': 'Sweet Breaker',
                                'image': 'https://i.imgur.com/msZulaU.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sweet_Breaker',
                                'type': 'Character',
                                'hyper': 'Melting Memories',
                                'availability': 'DLC 7 - Breaker Pack'},

            'nath' : {  'title': 'Nath',
                        'image': 'https://i.imgur.com/bziPTVX.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Nath',
                        'type': 'Character',
                        'hyper': 'Another Ultimate Weapon',
                        'availability': 'DLC 9 - Nath & Tomato+Mimyyuu Character Pack'},

            'tomato' : {'title': 'Tomato',
                        'image': 'https://i.imgur.com/8zGlVi0.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomato_%26_Mimyuu',
                        'type': 'Character',
                        'hyper': 'Waruda Machine, Blast Off!',
                        'availability': 'DLC 9 - Nath & Tomato+Mimyuu Character Pack'},
            'mimyuu' : {'title': 'Mimyuu',
                        'image': 'https://i.imgur.com/qMDobvc.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomato_%26_Mimyuu',
                        'type': 'Character',
                        'hyper': 'Evil Spy Work - Preparation',
                        'availability': 'DLC 9 - Nath & Tomato+Mimyuu Character Pack'},

            'kiriko' : {'title': 'Kiriko',
                        'image': 'https://i.imgur.com/BkwRxC5.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kiriko',
                        'type': 'Character',
                        'hyper': 'Final Surgery',
                        'availability' : 'DLC 11 - Kiriko & NoName Character Pack'},

            'noname' : {'title': 'NoName',
                        'image': 'https://i.imgur.com/a37fkTi.png',
                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/NoName',
                        'type': 'Character',
                        'hyper': 'Overseer',
                        'availability': 'DLC 11 - Kiriko & NoName Character Pack'},
            'noname (head)' : { 'title': 'NoName (Head)',
                                'image': 'https://i.imgur.com/asg3Nmr.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/NoName',
                                'type': 'Character',
                                'hyper': 'Overseer',
                                'availability': 'DLC 11 - Kiriko & NoName Character Pack',
                                'flavor': 'Insert pothead joke here'},

            'miusaki' : {   'title': 'Miusaki',
                            'image': 'https://i.imgur.com/RZsaz7w.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Miusaki',
                            'type': 'Character',
                            'hyper': 'Solid Witch',
                            'availability': 'DLC 13 - Witch Pack'},

            'ceoreparque' : {   'title': 'Ceoreparque',
                                'image': 'https://i.imgur.com/lyFWf0h.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Ceoreparque',
                                'type': 'Character',
                                'hyper': 'Witch\'s Hair Lock',
                                'availability': 'DLC 13 - Witch Pack'},

            'yuki (dangerous)' : {  'title': 'Yuki (Dangerous)',
                                    'image': 'https://i.imgur.com/Vc53vxy.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Yuki_(Dangerous)',
                                    'type': 'Character',
                                    'hyper': 'Evil Mastermind',
                                    'availability': 'DLC 15 - Yuki & Tomomo Renewal Pack'},

            'tomomo (casual)' : {   'title': 'Tomomo (Casual)',
                                    'image': 'https://i.imgur.com/YqmmkBh.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo_(Casual_%26_Sweet_Eater)',
                                    'type': 'Character',
                                    'hyper': 'Miracle Red Bean Ice Cream',
                                    'availability': 'DLC 15 - Yuki & Tomomo Renewal Pack',
                                    'flavor': 'This isn\'t even my final form!'},
            'tomomo (sweet eater)' : {  'title': 'Tomomo (Sweet Eater)',
                                        'image': 'https://i.imgur.com/TNSddat.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo_(Casual_%26_Sweet_Eater)',
                                        'type': 'Character',
                                        'hyper': 'Magical Revenge',
                                        'availability': 'DLC 15 - Yuki & Tomomo Renewal Pack',
                                        'flavor': 'Hide yo kids, hide yo wife, and hide yo husband...'},

            'qp (dangerous)' : {'title': 'QP (Dangerous)',
                                'image': 'https://i.imgur.com/9hrzCBb.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/QP_(Dangerous)',
                                'type': 'Character',
                                'hyper': 'Sweet Guardian',
                                'availability': 'Bonus - QP Shooting - Dangerous!!',
                                'flavor': 'Dangerous Pudding: ATK +1, Bad Pudding: DEF +1, Pudding: EVD +1'},

            'marie poppo (mixed)' : {   'title': 'Marie Poppo (Mixed)',
                                        'image': 'https://i.imgur.com/G7kJpzX.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marie_Poppo_(Mixed)',
                                        'type': 'Character',
                                        'hyper': 'Subspace Tunnel',
                                        'availability': 'Bonus - 200% Mixed Juice!'},

            'sora (military)' : {   'title': 'Sora (Military)',
                                    'image': 'https://i.imgur.com/gQESej5.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sora_(Military)',
                                    'type': 'Character',
                                    'hyper': 'Awakening of Talent',
                                    'availability': 'Bonus - Sora'},

            'aru (scramble)' : {    'title': 'Aru (Scramble)',
                                    'image': 'https://i.imgur.com/Rl3qAEg.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Aru_(Scramble)',
                                    'type': 'Character',
                                    'hyper': 'Santa\'s Job',
                                    'availability': 'Bonus - Xmas Shooting - Scramble!!'},

            'suguri (ver.2)' : {    'title': 'Suguri (ver.2)',
                                    'image': 'https://i.imgur.com/Nm0ZNz0.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Suguri_(Ver.2)',
                                    'type': 'Character',
                                    'hyper': 'Revival of Stars',
                                    'availability': 'Bonus - Acceleration of SUGURI 2'},

            ##################################
            # Character-specific Hyper cards
            ##################################

            'protagonist\'s privilege' : {  'title': 'Protagonist\'s Privilege',
                                            'image': 'https://i.imgur.com/1ctDbZw.png',
                                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kai/Hyper',
                                            'type': 'Hyper'},

            'hyper mode' : {'title': 'Hyper Mode',
                            'image': 'https://i.imgur.com/tX1EMuN.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/QP/Hyper',
                            'type': 'Hyper'},

            'accelerator' : {   'title': 'Accelerator',
                                'image': 'https://i.imgur.com/zwxOssW.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Suguri/Hyper',
                                'type': 'Hyper',
                                'flavor': 'IM ACCELERATING'},

            'x16 big rocket' : {'title': 'x16 Big Rocket',
                                'image': 'https://i.imgur.com/42GG1KI.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marc/Hyper',
                                'type': 'Hyper'},

            'gamble!' : {   'title': 'Gamble!',
                            'image': 'https://i.imgur.com/GCvfufb.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Yuki/Hyper',
                            'type': 'Hyper',
                            'flavor': 'You end up killing yourself half of the time, but...'},

            'present for you' : {   'title': 'Present For You',
                                    'image': 'https://i.imgur.com/0Mlr5Pk.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Aru/Hyper',
                                    'type': 'Hyper'},

            'binding chains' : {'title': 'Binding Chains',
                                'image': 'https://i.imgur.com/9745ZAZ.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Hime/Hyper',
                                'type': 'Hyper'},

            'extraordinary specs' : {   'title': 'Extraordinary Specs',
                                        'image': 'https://i.imgur.com/JrPSZiP.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sora/Hyper',
                                        'type': 'Hyper',
                                        'flavor': '\"I hate RNG but I still play this game\"'},

            'air strike' : {'title': 'Air Strike',
                            'image': 'https://i.imgur.com/XZEoVAF.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Fernet/Hyper',
                            'type': 'Hyper',
                            'flavor': 'OHOHOHOHOHO'},

            'blue crow the second' : {  'title': 'Blue Crow the Second',
                                        'image': 'https://i.imgur.com/hMbzDij.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Peat/Hyper',
                                        'type': 'Hyper'},

            'ubiquitous' : {'title': 'Ubiquitous',
                            'image': 'https://i.imgur.com/Xmqkq2y.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marie_Poppo/Hyper',
                            'type': 'Hyper'},

            'magical massacre' : {  'title': 'Magical Massacre',
                                    'image': 'https://i.imgur.com/KUuqiIP.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo/Hyper',
                                    'type': 'Hyper'},

            'golden egg' : {'title': 'Golden Egg',
                            'image': 'https://i.imgur.com/xVLJANx.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Chicken',
                            'type': 'Hyper'},

            'reflective shell' : {  'title': 'Reflective Shell',
                                    'image': 'https://i.imgur.com/6i6d5cC.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Robo_Ball',
                                    'type': 'Hyper'},

            'jonathan rush' : {     'title': 'Jonathan Rush',
                                    'image': 'https://i.imgur.com/FjcPkqs.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Seagull',
                                    'type': 'Hyper'},

            'banned for life' : {   'title': 'Banned For Life',
                                    'image': 'https://i.imgur.com/3aPfYfR.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Store_Manager/Hyper',
                                    'type': 'Hyper'},

            'turbo charged' : { 'title': 'Turbo Charged',
                                'image': 'https://i.imgur.com/ABpCWN2.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Shifu_Robot',
                                'type': 'Hyper'},

            'immovable object' : {  'title': 'Immovable Object',
                                    'image': 'https://i.imgur.com/88NxwAP.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Flying_Castle/Hyper',
                                    'type': 'Hyper'},

            'beyond hell' : {   'title': 'Beyond Hell',
                                'image': 'https://i.imgur.com/XnotI3o.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Syura',
                                'type': 'Hyper'},

            'deploy bits' : {   'title': 'Deploy Bits',
                                'image': 'https://i.imgur.com/qBZzuGQ.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Nanako',
                                'type': 'Hyper',
                                'flavor': 'ビット食えよおおお！！'},

            'big bang bell' : { 'title': 'Big Bang Bell',
                                'image': 'https://i.imgur.com/EQT6d28.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Saki',
                                'type': 'Hyper'},

            'cast off' : {  'title': 'Cast Off',
                            'image': 'https://i.imgur.com/Iw06XYi.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kyousuke',
                            'type': 'Hyper'},

            'plushie master' : {    'title': 'Plushie Master',
                                    'image': 'https://i.imgur.com/FttL26C.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Krila/Hyper',
                                    'type': 'Hyper'},
            'dance, long-eared beasts!' : { 'title': 'Dance, Long-Eared Beasts!',
                                            'image': 'https://i.imgur.com/Qya5Kwy.png',
                                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Krila/Hyper',
                                            'type': 'Hyper'},

            'blazing!' : {  'title': 'Blazing!',
                            'image': 'https://i.imgur.com/hxtgTEt.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kae/Hyper',
                            'type': 'Hyper'},

            'self-destruct' : { 'title': 'Self-Destruct',
                                'image': 'https://i.imgur.com/ua36HaN.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Alte',
                                'type': 'Hyper'},

            'crystal barrier' : {   'title': 'Crystal Barrier',
                                    'image': 'https://i.imgur.com/5g3TQTt.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kyoko/Hyper',
                                    'type': 'Hyper'},

            'delta field' : {   'title': 'Delta Field',
                                'image': 'https://i.imgur.com/TkH4pAy.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sham',
                                'type': 'Hyper'},

            'whimsical windmill' : {'title': 'Whimsical Windmill',
                                    'image': 'https://i.imgur.com/PkoXGcs.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sherry/Hyper',
                                    'type': 'Hyper'},

            'star blasting fuse' : {'title': 'Star Blasting Fuse',
                                    'image': 'https://i.imgur.com/PlcPxzV.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Star_Breaker/Hyper',
                                    'type': 'Hyper'},
            'invisible bomb' : {'title': 'Invisible Bomb',
                                'image': 'https://i.imgur.com/UMzUXJX.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Star_Breaker/Hyper',
                                'type': 'Hyper'},

            'melting memories' : {  'title': 'Melting Memories',
                                    'image': 'https://i.imgur.com/QmutVPW.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sweet_Breaker/Hyper',
                                    'type': 'Hyper'},

            'another ultimate weapon' : {   'title': 'Another Ultimate Weapon',
                                            'image': 'https://i.imgur.com/zY47TWj.png',
                                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Nath/Hyper',
                                            'type': 'Hyper'},

            'waruda machine, blast off!' : {'title': 'Waruda Machine, Blast Off!',
                                            'image': 'https://i.imgur.com/cps0XmS.png',
                                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomato_%26_Mimyuu',
                                            'type': 'Hyper'},
            'evil spy work - preparation' : {   'title': 'Evil Spy Work - Preparation',
                                                'image': 'https://i.imgur.com/cM4CQmY.png',
                                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomato_%26_Mimyuu',
                                                'type': 'Hyper'},
            'evil spy work - execution' : { 'title' : 'Evil Spy Work - Execution',
                                            'image': 'https://i.imgur.com/XxIkeqd.png',
                                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomato_%26_Mimyuu',
                                            'type': 'Hyper'},

            'final surgery' : { 'title': 'Final Surgery',
                                'image': 'https://i.imgur.com/XDQHK64.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Kiriko/Hyper',
                                'type': 'Hyper'},

            'overseer' : {  'title': 'Overseer',
                            'image': 'https://i.imgur.com/0xWniIR.png',
                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/NoName',
                            'type': 'Hyper'},

            'solid witch' : {   'title': 'Solid Witch',
                                'image': 'https://i.imgur.com/G4QXV03.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Miusaki',
                                'type': 'Hyper'},

            'witch\'s hair lock' : {'title': 'Witch\'s Hair Lock',
                                    'image': 'https://i.imgur.com/iOb2a6w.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Ceoreparque/Hyper',
                                    'type': 'Hyper'},

            'evil mastermind' : {   'title': 'Evil Mastermind',
                                    'image': 'https://i.imgur.com/5WEnLTA.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Yuki_(Dangerous)/Hyper',
                                    'type': 'Hyper'},

            'miracle red bean ice cream' : {'title': 'Miracle Red Bean Ice Cream',
                                            'image': 'https://i.imgur.com/QQCS1Gc.png',
                                            'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo_(Casual_%26_Sweet_Eater)/Hyper',
                                            'type': 'Hyper',
                                            'flavor': 'The beginning of the end'},
            'magical revenge' : {   'title': 'Magical Revenge',
                                    'image': 'https://i.imgur.com/7hXMmaM.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Tomomo_(Casual_%26_Sweet_Eater)/Hyper',
                                    'type': 'Hyper'},

            'sweet guardian' : {'title': 'Sweet Guardian',
                                'image': 'https://i.imgur.com/j8wT0Pd.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/QP_(Dangerous)',
                                'type': 'Hyper'},

            'subspace tunnel' : {   'title': 'Subspace Tunnel',
                                    'image': 'https://i.imgur.com/7hUO30x.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marie_Poppo_(Mixed)',
                                    'type': 'Hyper'},

            'awakening of talent' : {   'title': 'Awakening of Talent',
                                        'image': 'https://i.imgur.com/LlbRAlO.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Sora_(Military)/Hyper',
                                        'type': 'Hyper'},

            'santa\'s job' : {  'title': 'Santa\'s Job',
                                'image': 'https://i.imgur.com/BmeHYHk.png',
                                'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Aru_(Scramble)',
                                'type': 'Hyper'},

            'revival of stars' : {  'title': 'Revival of Stars',
                                    'image': 'https://i.imgur.com/DIjXcjg.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Suguri_(Ver.2)/Hyper',
                                    'type': 'Hyper'},

            ##################################
            # Enemies
            ##################################
            'chicken (enemy)' : {   'title': 'Chicken (Enemy)',
                                    'image': 'https://i.imgur.com/Q9OWCiE.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Chicken#Wild%20Unit',
                                    'type': 'Enemy'},

            'robo ball (enemy)' : { 'title': 'Robo Ball (Enemy)',
                                    'image': 'https://i.imgur.com/V3McZmS.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Robo_Ball',
                                    'type': 'Enemy'},

            'seagull (enemy)' : {   'title': 'Seagull (Enemy)',
                                    'image': 'https://i.imgur.com/lxAj83U.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Seagull',
                                    'type': 'Enemy'},

            'store manager (boss)' : {  'title': 'Store Maanger (Boss)',
                                        'image': 'https://i.imgur.com/ppZUnDJ.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Store_Manager',
                                        'type': 'Enemy'},

            'shifu robot (boss)' : {'title': 'Shifu Robot (Boss)',
                                    'image': 'https://i.imgur.com/iuepgcZ.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Shifu_Robot',
                                    'type': 'Enemy'},

            'flying castle (boss)' : {  'title': 'Flying Castle (Boss)',
                                        'image': 'https://i.imgur.com/1Fbh8NW.png',
                                        'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Flying_Castle',
                                        'type': 'Enemy'},

            'marie poppo (boss)' : {'title': 'Marie Poppo (Boss)',
                                    'image': 'https://i.imgur.com/9njXgnd.png',
                                    'source': 'http://onehundredpercentorangejuice.wikia.com/wiki/Marie_Poppo',
                                    'type': 'Enemy'},

         }
